/** Retrato de cada Presidente (frontend/public/img/presidentes/<id>.jpg): crédito e licença do Wikimedia Commons. */
export const CREDITOS_FOTO: Record<string, { credito: string; licenca: string; pagina: string }> = {
  'deodoro': { credito: "Bror Kronstrand", licenca: "Domínio público", pagina: "https://commons.wikimedia.org/wiki/File:Deodoro_da_Fonseca_sak.jpg" },
  'floriano': { credito: "Autor desconhecido", licenca: "Domínio público", pagina: "https://commons.wikimedia.org/wiki/File:Florianovieirapeixoto.jpg" },
  'prudente': { credito: "Governo do Brasil", licenca: "Domínio público", pagina: "https://commons.wikimedia.org/wiki/File:Prudentedemorais.jpg" },
  'campos-sales': { credito: "Governo do Brasil", licenca: "Domínio público", pagina: "https://commons.wikimedia.org/wiki/File:Campos_Sales.jpg" },
  'rodrigues-alves': { credito: "Governo do Brasil", licenca: "Domínio público", pagina: "https://commons.wikimedia.org/wiki/File:Rodrigues_Alves_3.jpg" },
  'afonso-pena': { credito: "Governo do Brasil", licenca: "Domínio público", pagina: "https://commons.wikimedia.org/wiki/File:Afonso_Pena.jpg" },
  'nilo-pecanha': { credito: "Governo do Brasil", licenca: "Domínio público", pagina: "https://commons.wikimedia.org/wiki/File:Nilo_Pe%C3%A7anha_02.jpg" },
  'hermes': { credito: "Governo do Brasil", licenca: "Domínio público", pagina: "https://commons.wikimedia.org/wiki/File:Hermes_da_Fonseca_(1910).jpg" },
  'venceslau': { credito: "Malta", licenca: "Domínio público", pagina: "https://commons.wikimedia.org/wiki/File:Venceslau_Br%C3%A1s_(retrato_oval).jpg" },
  'delfim': { credito: "Autor desconhecido", licenca: "Domínio público", pagina: "https://commons.wikimedia.org/wiki/File:Delfim_Moreira,_sem_data.tif" },
  'epitacio': { credito: "Acervo público", licenca: "Domínio público", pagina: "https://commons.wikimedia.org/wiki/File:Epitacio_Pessoa.jpg" },
  'bernardes': { credito: "Governo do Brasil", licenca: "Domínio público", pagina: "https://commons.wikimedia.org/wiki/File:Artur_Bernardes_(1922).jpg" },
  'washington-luis': { credito: "Autor desconhecido", licenca: "Domínio público", pagina: "https://commons.wikimedia.org/wiki/File:Washington_Lu%C3%ADs,_presidente_do_Brasil,_1926.jpg" },
  'vargas': { credito: "Governo do Brasil", licenca: "Domínio público", pagina: "https://commons.wikimedia.org/wiki/File:Getulio_Vargas_(1930).jpg" },
  'linhares': { credito: "Agência Brasil", licenca: "CC BY 3.0 br", pagina: "https://commons.wikimedia.org/wiki/File:JoseLinhares.jpg" },
  'dutra': { credito: "Governo do Brasil", licenca: "Domínio público", pagina: "https://commons.wikimedia.org/wiki/File:GASPARDUTRA.jpg" },
  'cafe-filho': { credito: "Presidência da República", licenca: "Domínio público", pagina: "https://commons.wikimedia.org/wiki/File:Caf%C3%A9_Filho.jpg" },
  'carlos-luz': { credito: "Governo do Brasil", licenca: "Domínio público", pagina: "https://commons.wikimedia.org/wiki/File:CarlosLuz.jpg" },
  'nereu': { credito: "Governo do Brasil", licenca: "Domínio público", pagina: "https://commons.wikimedia.org/wiki/File:Presidente_Nereu_Ramos.jpg" },
  'jk': { credito: "Governo do Brasil", licenca: "Domínio público", pagina: "https://commons.wikimedia.org/wiki/File:Juscelino_Kubitschek_in_1956.jpg" },
  'janio': { credito: "Agência Brasil", licenca: "Domínio público", pagina: "https://commons.wikimedia.org/wiki/File:J%C3%A2nio_Quadros,_presidente_do_Brasil_(1961).jpg" },
  'mazzilli': { credito: "Governo do Brasil", licenca: "Domínio público", pagina: "https://commons.wikimedia.org/wiki/File:Ranieri_Mazzilli_(1961).jpg" },
  'jango': { credito: "Governo do Brasil", licenca: "Domínio público", pagina: "https://commons.wikimedia.org/wiki/File:MO_63.2240.2_-_Photograph_of_Jo%C3%A3o_Goulart_President_of_the_Republic_of_Brazil_(cropped).jpg" },
  'castelo': { credito: "Governo do Brasil", licenca: "Domínio público", pagina: "https://commons.wikimedia.org/wiki/File:Humberto_Castelo_Branco,_presidente_do_Brasil,_1964.jpg" },
  'costa-e-silva': { credito: "Governo do Brasil", licenca: "Domínio público", pagina: "https://commons.wikimedia.org/wiki/File:Costa_e_Silva.jpg" },
  'medici': { credito: "Autor desconhecido", licenca: "Domínio público", pagina: "https://commons.wikimedia.org/wiki/File:Em%C3%ADlio_Garrastazu_M%C3%A9dici,_presidente_da_Rep%C3%BAblica._(cropped_and_contrast_enhanced).tif" },
  'geisel': { credito: "Governo do Brasil", licenca: "Domínio público", pagina: "https://commons.wikimedia.org/wiki/File:Foto_oficial_de_Ernesto_Geisel_(corre%C3%A7%C3%A3o_de_cor).png" },
  'figueiredo': { credito: "Governo do Brasil", licenca: "Domínio público", pagina: "https://commons.wikimedia.org/wiki/File:Jo%C3%A3o_Figueiredo,_presidente_do_Brasil,_1979_(vers%C3%A3o_colorida).jpg" },
  'tancredo': { credito: "Biblioteca da Presidência do Brasil", licenca: "Domínio público", pagina: "https://commons.wikimedia.org/wiki/File:Retrato_oficial_do_presidente_do_Brasil,_Tancredo_Neves.jpg" },
  'sarney': { credito: "EBC", licenca: "CC BY 3.0 br", pagina: "https://commons.wikimedia.org/wiki/File:Foto_Oficial_Sarney_EBC.jpg" },
  'collor': { credito: "Ubirajara Dettimar/Presidência da República", licenca: "CC BY-SA 2.0", pagina: "https://commons.wikimedia.org/wiki/File:Foto_oficial_do_presidente_Fernando_Collor_de_Melo._(38405801411).jpg" },
  'itamar': { credito: "Radiobrás", licenca: "CC BY 3.0 br", pagina: "https://commons.wikimedia.org/wiki/File:Itamar_Franco.jpg" },
  'fhc': { credito: "Agência Brasil", licenca: "CC BY 3.0 br", pagina: "https://commons.wikimedia.org/wiki/File:Fernando_Henrique_Cardoso_(1999).jpg" },
  'lula': { credito: "Palácio do Planalto", licenca: "CC BY 2.0", pagina: "https://commons.wikimedia.org/wiki/File:Foto_oficial_de_Luiz_In%C3%A1cio_Lula_da_Silva_(estreita).jpg" },
  'dilma': { credito: "Roberto Stuckert Filho/Presidência da República", licenca: "Atribuição", pagina: "https://commons.wikimedia.org/wiki/File:Dilma_Rousseff_-_foto_oficial_2011-01-09.jpg" },
  'temer': { credito: "Beto Barata/PR", licenca: "CC BY 2.0", pagina: "https://commons.wikimedia.org/wiki/File:Presidente_Michel_Temer_(foto_oficial)_-_cortada.jpg" },
  'bolsonaro': { credito: "US Embassy Brasília", licenca: "Domínio público", pagina: "https://commons.wikimedia.org/wiki/File:Presidente_Jair_Messias_Bolsonaro.jpg" },
};
