/**
 * Presidentes da República desde 1889, no mesmo formato para todos: como chegou ao cargo, como
 * saiu e marcos institucionais objetivos (Constituições, emendas, leis com número, moedas, obras,
 * guerras e fatos históricos registrados oficialmente). Nenhuma avaliação de governo.
 *
 * Datas de início e fim do exercício como na Galeria dos Presidentes da Biblioteca da Presidência
 * da República; leis e emendas citadas pelo número oficial.
 */

export interface Presidencia {
  id: string;
  /** Arquivo do retrato (public/presidentes/<foto>.jpg); juntas não têm. */
  foto: string | null;
  nome: string;
  /** Integrantes, quando o governo foi exercido por uma junta. */
  junta?: string[];
  inicio: string;
  /** null = em exercício. */
  fim: string | null;
  chegada: string;
  saida: string | null;
  marcos: string[];
  /** Observação (ex.: interinidade, eleito que não tomou posse). */
  nota?: string;
  /** Eleito que não chegou a exercer (Tancredo Neves). */
  naoExerceu?: boolean;
}

export interface Era {
  id: string;
  nome: string;
  inicio: string;
  fim: string | null;
  resumo: string;
}

export const ERAS: Era[] = [
  {
    id: 'primeira-republica',
    nome: 'Primeira República',
    inicio: '1889-11-15',
    fim: '1930-10-24',
    resumo: 'Da Proclamação da República à Revolução de 1930. Constituição de 1891, eleições diretas com voto aberto e restrito.',
  },
  {
    id: 'era-vargas',
    nome: 'Era Vargas',
    inicio: '1930-10-24',
    fim: '1945-10-29',
    resumo: 'Governo Provisório, Constituição de 1934 e Estado Novo (Constituição de 1937), até a deposição de Getúlio Vargas.',
  },
  {
    id: 'republica-1946',
    nome: 'República de 1946',
    inicio: '1945-10-29',
    fim: '1964-04-01',
    resumo: 'Constituição de 1946, eleições diretas para presidente e mudança da capital para Brasília.',
  },
  {
    id: 'governos-militares',
    nome: 'Governos militares',
    inicio: '1964-04-01',
    fim: '1985-03-15',
    resumo: 'Presidentes eleitos de forma indireta, Atos Institucionais e Constituição de 1967, até a abertura política.',
  },
  {
    id: 'nova-republica',
    nome: 'Nova República',
    inicio: '1985-03-15',
    fim: null,
    resumo: 'Constituição de 1988 e eleições diretas para presidente desde 1989.',
  },
];

export const PRESIDENCIAS: Presidencia[] = [
  {
    id: 'deodoro',
    foto: 'deodoro',
    nome: 'Deodoro da Fonseca',
    inicio: '1889-11-15',
    fim: '1891-11-23',
    chegada: 'Chefe do Governo Provisório após a Proclamação da República; eleito pelo Congresso Constituinte em 25/02/1891.',
    saida: 'Renúncia, depois de decretar a dissolução do Congresso.',
    marcos: ['Proclamação da República (15/11/1889)', 'Separação entre Igreja e Estado (Decreto 119-A, de 1890)', 'Primeira Constituição da República (24/02/1891)'],
  },
  {
    id: 'floriano',
    foto: 'floriano',
    nome: 'Floriano Peixoto',
    inicio: '1891-11-23',
    fim: '1894-11-15',
    chegada: 'Vice-presidente; assumiu com a renúncia de Deodoro da Fonseca.',
    saida: 'Fim do mandato.',
    marcos: ['Revolta da Armada (1893–1894)', 'Revolução Federalista, no Sul (1893–1895)'],
  },
  {
    id: 'prudente',
    foto: 'prudente',
    nome: 'Prudente de Morais',
    inicio: '1894-11-15',
    fim: '1898-11-15',
    chegada: 'Eleição direta; primeiro presidente civil.',
    saida: 'Fim do mandato.',
    marcos: ['Guerra de Canudos (1896–1897)'],
    nota: 'Afastado por doença de novembro de 1896 a março de 1897; o vice, Manuel Vitorino, exerceu a Presidência.',
  },
  {
    id: 'campos-sales',
    foto: 'campos-sales',
    nome: 'Campos Sales',
    inicio: '1898-11-15',
    fim: '1902-11-15',
    chegada: 'Eleição direta.',
    saida: 'Fim do mandato.',
    marcos: ['Renegociação da dívida externa (funding loan), acertada em 1898', '“Política dos governadores”, acordo entre o governo federal e os governos estaduais'],
  },
  {
    id: 'rodrigues-alves',
    foto: 'rodrigues-alves',
    nome: 'Rodrigues Alves',
    inicio: '1902-11-15',
    fim: '1906-11-15',
    chegada: 'Eleição direta.',
    saida: 'Fim do mandato.',
    marcos: ['Tratado de Petrópolis (1903): o Acre passa a integrar o Brasil', 'Reforma urbana e vacinação obrigatória no Rio de Janeiro; Revolta da Vacina (1904)'],
    nota: 'Eleito de novo em 1918, morreu em janeiro de 1919 sem tomar posse.',
  },
  {
    id: 'afonso-pena',
    foto: 'afonso-pena',
    nome: 'Afonso Pena',
    inicio: '1906-11-15',
    fim: '1909-06-14',
    chegada: 'Eleição direta.',
    saida: 'Morte no cargo.',
    marcos: ['Comissão Rondon: linhas telegráficas de Mato Grosso ao Amazonas (a partir de 1907)', 'Incentivo à imigração e expansão das ferrovias'],
  },
  {
    id: 'nilo-pecanha',
    foto: 'nilo-pecanha',
    nome: 'Nilo Peçanha',
    inicio: '1909-06-14',
    fim: '1910-11-15',
    chegada: 'Vice-presidente; assumiu com a morte de Afonso Pena.',
    saida: 'Fim do mandato.',
    marcos: ['Escolas de Aprendizes Artífices (Decreto 7.566, de 1909), origem da rede federal de ensino técnico', 'Criação do Serviço de Proteção aos Índios (1910)'],
  },
  {
    id: 'hermes',
    foto: 'hermes',
    nome: 'Hermes da Fonseca',
    inicio: '1910-11-15',
    fim: '1914-11-15',
    chegada: 'Eleição direta.',
    saida: 'Fim do mandato.',
    marcos: ['Revolta da Chibata (1910)', 'Guerra do Contestado (1912–1916)'],
  },
  {
    id: 'venceslau',
    foto: 'venceslau',
    nome: 'Venceslau Brás',
    inicio: '1914-11-15',
    fim: '1918-11-15',
    chegada: 'Eleição direta.',
    saida: 'Fim do mandato.',
    marcos: ['Código Civil (Lei 3.071, de 1916)', 'Greve geral de 1917', 'Entrada do Brasil na Primeira Guerra Mundial (1917)'],
  },
  {
    id: 'delfim',
    foto: 'delfim',
    nome: 'Delfim Moreira',
    inicio: '1918-11-15',
    fim: '1919-07-28',
    chegada: 'Vice-presidente; assumiu porque o presidente eleito, Rodrigues Alves, adoeceu e morreu sem tomar posse.',
    saida: 'Posse do presidente escolhido em nova eleição (1919).',
    marcos: ['Nova eleição presidencial (abril de 1919)'],
  },
  {
    id: 'epitacio',
    foto: 'epitacio',
    nome: 'Epitácio Pessoa',
    inicio: '1919-07-28',
    fim: '1922-11-15',
    chegada: 'Eleição direta (eleição de 1919).',
    saida: 'Fim do mandato.',
    marcos: ['Centenário da Independência (1922) e primeira transmissão pública de rádio no país', 'Revolta dos 18 do Forte de Copacabana (1922)'],
  },
  {
    id: 'bernardes',
    foto: 'bernardes',
    nome: 'Artur Bernardes',
    inicio: '1922-11-15',
    fim: '1926-11-15',
    chegada: 'Eleição direta.',
    saida: 'Fim do mandato.',
    marcos: ['Estado de sítio durante a maior parte do mandato', 'Revolta de 1924 em São Paulo e Coluna Prestes (1925–1927)', 'Reforma da Constituição de 1891 (1926)'],
  },
  {
    id: 'washington-luis',
    foto: 'washington-luis',
    nome: 'Washington Luís',
    inicio: '1926-11-15',
    fim: '1930-10-24',
    chegada: 'Eleição direta.',
    saida: 'Deposto pela Revolução de 1930; o eleito em março de 1930, Júlio Prestes, não tomou posse.',
    marcos: ['Rodovias Rio–São Paulo e Rio–Petrópolis (1928)', 'Crise econômica mundial de 1929 e queda do preço do café'],
  },
  {
    id: 'junta-1930',
    foto: null,
    nome: 'Junta Governativa Provisória de 1930',
    junta: ['General Augusto Tasso Fragoso', 'General João de Deus Mena Barreto', 'Almirante José Isaías de Noronha'],
    inicio: '1930-10-24',
    fim: '1930-11-03',
    chegada: 'Assumiu com a deposição de Washington Luís.',
    saida: 'Entregou o governo a Getúlio Vargas.',
    marcos: [],
  },
  {
    id: 'vargas-1930',
    foto: 'vargas',
    nome: 'Getúlio Vargas',
    inicio: '1930-11-03',
    fim: '1945-10-29',
    chegada: 'Chefe do Governo Provisório após a Revolução de 1930; eleito pela Assembleia Constituinte em 1934; a partir de 1937, no Estado Novo.',
    saida: 'Deposto pelos militares.',
    marcos: [
      'Código Eleitoral de 1932: voto secreto, voto feminino e criação da Justiça Eleitoral',
      'Revolução Constitucionalista (1932), Constituição de 1934 e Constituição de 1937 (Estado Novo)',
      'Consolidação das Leis do Trabalho (1943) e participação na Segunda Guerra Mundial (1942–1945)',
    ],
  },
  {
    id: 'linhares',
    foto: 'linhares',
    nome: 'José Linhares',
    inicio: '1945-10-29',
    fim: '1946-01-31',
    chegada: 'Presidente do Supremo Tribunal Federal; assumiu com a deposição de Getúlio Vargas.',
    saida: 'Posse do presidente eleito.',
    marcos: ['Eleições de 2 de dezembro de 1945, para presidente e para a Assembleia Constituinte'],
  },
  {
    id: 'dutra',
    foto: 'dutra',
    nome: 'Eurico Gaspar Dutra',
    inicio: '1946-01-31',
    fim: '1951-01-31',
    chegada: 'Eleição direta (1945).',
    saida: 'Fim do mandato.',
    marcos: ['Constituição de 1946 (18/09/1946)', 'Proibição dos jogos de azar (Decreto-Lei 9.215, de 1946)'],
  },
  {
    id: 'vargas-1951',
    foto: 'vargas',
    nome: 'Getúlio Vargas',
    inicio: '1951-01-31',
    fim: '1954-08-24',
    chegada: 'Eleição direta (1950).',
    saida: 'Morte no cargo (suicídio).',
    marcos: ['Criação do BNDE, atual BNDES (1952)', 'Criação da Petrobras (Lei 2.004, de 1953)'],
  },
  {
    id: 'cafe-filho',
    foto: 'cafe-filho',
    nome: 'Café Filho',
    inicio: '1954-08-24',
    fim: '1955-11-08',
    chegada: 'Vice-presidente; assumiu com a morte de Getúlio Vargas.',
    saida: 'Afastou-se por motivo de saúde e foi impedido pelo Congresso de reassumir.',
    marcos: ['Eleição presidencial de outubro de 1955'],
  },
  {
    id: 'carlos-luz',
    foto: 'carlos-luz',
    nome: 'Carlos Luz',
    inicio: '1955-11-08',
    fim: '1955-11-11',
    chegada: 'Presidente da Câmara dos Deputados; assumiu com o afastamento de Café Filho.',
    saida: 'Deposto no movimento militar de 11 de novembro de 1955, que assegurou a posse do presidente eleito.',
    marcos: [],
  },
  {
    id: 'nereu',
    foto: 'nereu',
    nome: 'Nereu Ramos',
    inicio: '1955-11-11',
    fim: '1956-01-31',
    chegada: 'Vice-presidente do Senado; assumiu por decisão do Congresso Nacional.',
    saida: 'Posse do presidente eleito.',
    marcos: ['Estado de sítio até a posse do presidente eleito'],
  },
  {
    id: 'jk',
    foto: 'jk',
    nome: 'Juscelino Kubitschek',
    inicio: '1956-01-31',
    fim: '1961-01-31',
    chegada: 'Eleição direta (1955).',
    saida: 'Fim do mandato.',
    marcos: ['Plano de Metas', 'Criação da Sudene (1959)', 'Inauguração de Brasília, nova capital (21/04/1960)'],
  },
  {
    id: 'janio',
    foto: 'janio',
    nome: 'Jânio Quadros',
    inicio: '1961-01-31',
    fim: '1961-08-25',
    chegada: 'Eleição direta (1960).',
    saida: 'Renúncia.',
    marcos: [],
  },
  {
    id: 'mazzilli-1961',
    foto: 'mazzilli',
    nome: 'Ranieri Mazzilli',
    inicio: '1961-08-25',
    fim: '1961-09-07',
    chegada: 'Presidente da Câmara dos Deputados; assumiu interinamente com a renúncia de Jânio Quadros.',
    saida: 'Posse do vice-presidente, João Goulart.',
    marcos: ['Adoção do parlamentarismo (Emenda Constitucional 4, de 1961)'],
  },
  {
    id: 'jango',
    foto: 'jango',
    nome: 'João Goulart',
    inicio: '1961-09-07',
    fim: '1964-04-01',
    chegada: 'Vice-presidente; assumiu após a renúncia de Jânio Quadros, sob o parlamentarismo.',
    saida: 'Deposto pelo golpe militar de 1964; em 02/04/1964 o Congresso declarou vaga a Presidência.',
    marcos: ['13º salário (Lei 4.090, de 1962)', 'Plebiscito de 1963: volta do presidencialismo', 'Estatuto do Trabalhador Rural (1963)'],
  },
  {
    id: 'mazzilli-1964',
    foto: 'mazzilli',
    nome: 'Ranieri Mazzilli',
    inicio: '1964-04-02',
    fim: '1964-04-15',
    chegada: 'Presidente da Câmara dos Deputados; assumiu interinamente quando o Congresso declarou vaga a Presidência.',
    saida: 'Posse do presidente eleito indiretamente pelo Congresso.',
    marcos: ['Ato Institucional nº 1 (09/04/1964)'],
  },
  {
    id: 'castelo',
    foto: 'castelo',
    nome: 'Castelo Branco',
    inicio: '1964-04-15',
    fim: '1967-03-15',
    chegada: 'Eleição indireta, pelo Congresso Nacional.',
    saida: 'Fim do mandato.',
    marcos: ['Criação do Banco Central (Lei 4.595, de 1964)', 'Ato Institucional nº 2 (1965): extinção dos partidos e bipartidarismo', 'Cruzeiro novo, nova moeda, e Constituição de 1967'],
  },
  {
    id: 'costa-e-silva',
    foto: 'costa-e-silva',
    nome: 'Costa e Silva',
    inicio: '1967-03-15',
    fim: '1969-08-31',
    chegada: 'Eleição indireta, pelo Congresso Nacional.',
    saida: 'Afastado por doença; morreu em dezembro de 1969.',
    marcos: ['Ato Institucional nº 5 (13/12/1968): recesso do Congresso e suspensão de garantias', 'Criação da Embraer (1969)'],
  },
  {
    id: 'junta-1969',
    foto: null,
    nome: 'Junta Militar de 1969',
    junta: ['General Aurélio de Lyra Tavares', 'Almirante Augusto Rademaker', 'Brigadeiro Márcio de Souza e Mello'],
    inicio: '1969-08-31',
    fim: '1969-10-30',
    chegada: 'Ministros militares; assumiram com o afastamento de Costa e Silva, sem a posse do vice-presidente, Pedro Aleixo.',
    saida: 'Posse do presidente eleito indiretamente pelo Congresso.',
    marcos: ['Emenda Constitucional 1, de 1969'],
  },
  {
    id: 'medici',
    foto: 'medici',
    nome: 'Emílio Garrastazu Médici',
    inicio: '1969-10-30',
    fim: '1974-03-15',
    chegada: 'Eleição indireta, pelo Congresso Nacional.',
    saida: 'Fim do mandato.',
    marcos: ['Período de alto crescimento econômico (1968–1973)', 'Criação do Incra (1970)', 'Rodovia Transamazônica (1972) e Ponte Rio–Niterói (1974)'],
  },
  {
    id: 'geisel',
    foto: 'geisel',
    nome: 'Ernesto Geisel',
    inicio: '1974-03-15',
    fim: '1979-03-15',
    chegada: 'Eleição indireta, pelo Colégio Eleitoral.',
    saida: 'Fim do mandato.',
    marcos: ['Início da abertura política', 'Lei do Divórcio (Lei 6.515, de 1977)', 'Fim do AI-5 (Emenda Constitucional 11, de 1978, em vigor em 01/01/1979)'],
  },
  {
    id: 'figueiredo',
    foto: 'figueiredo',
    nome: 'João Figueiredo',
    inicio: '1979-03-15',
    fim: '1985-03-15',
    chegada: 'Eleição indireta, pelo Colégio Eleitoral.',
    saida: 'Fim do mandato.',
    marcos: ['Lei da Anistia (Lei 6.683, de 1979) e volta do pluripartidarismo (1979)', 'Eleições diretas para governador (1982)', 'Campanha Diretas Já (1984)'],
  },
  {
    id: 'tancredo',
    foto: 'tancredo',
    nome: 'Tancredo Neves',
    inicio: '1985-03-15',
    fim: '1985-04-21',
    chegada: 'Eleito presidente pelo Colégio Eleitoral em 15/01/1985.',
    saida: 'Adoeceu na véspera da posse e morreu em 21/04/1985, sem assumir.',
    marcos: [],
    naoExerceu: true,
    nota: 'Incluído na galeria dos Presidentes da República pela Lei 7.465, de 1986.',
  },
  {
    id: 'sarney',
    foto: 'sarney',
    nome: 'José Sarney',
    inicio: '1985-03-15',
    fim: '1990-03-15',
    chegada: 'Vice-presidente eleito; assumiu interinamente em 15/03/1985 e, com a morte de Tancredo Neves, em definitivo.',
    saida: 'Fim do mandato.',
    marcos: ['Plano Cruzado (1986)', 'Constituição de 1988 (05/10/1988)', 'Eleição direta para presidente (1989), a primeira desde 1960'],
  },
  {
    id: 'collor',
    foto: 'collor',
    nome: 'Fernando Collor',
    inicio: '1990-03-15',
    fim: '1992-12-29',
    chegada: 'Eleição direta (1989).',
    saida: 'Afastado pela abertura do processo de impeachment (02/10/1992); renunciou em 29/12/1992, e o Senado o declarou inelegível por oito anos.',
    marcos: ['Plano Collor (1990)', 'Código de Defesa do Consumidor (Lei 8.078, de 1990)', 'Conferência da ONU sobre Meio Ambiente, a Rio-92 (1992)'],
  },
  {
    id: 'itamar',
    foto: 'itamar',
    nome: 'Itamar Franco',
    inicio: '1992-12-29',
    fim: '1995-01-01',
    chegada: 'Vice-presidente; exerceu a Presidência desde 02/10/1992 e assumiu em definitivo com a renúncia de Fernando Collor.',
    saida: 'Fim do mandato.',
    marcos: ['Plebiscito de 1993: república e presidencialismo', 'Plano Real e nova moeda, o real (1994)'],
  },
  {
    id: 'fhc',
    foto: 'fhc',
    nome: 'Fernando Henrique Cardoso',
    inicio: '1995-01-01',
    fim: '2003-01-01',
    chegada: 'Eleição direta (1994); reeleito em 1998.',
    saida: 'Fim do mandato.',
    marcos: ['Emenda da reeleição (Emenda Constitucional 16, de 1997)', 'Lei de Responsabilidade Fiscal (Lei Complementar 101, de 2000)', 'Privatizações e criação das agências reguladoras'],
  },
  {
    id: 'lula-2003',
    foto: 'lula',
    nome: 'Luiz Inácio Lula da Silva',
    inicio: '2003-01-01',
    fim: '2011-01-01',
    chegada: 'Eleição direta (2002); reeleito em 2006.',
    saida: 'Fim do mandato.',
    marcos: ['Reforma da Previdência dos servidores (Emenda Constitucional 41, de 2003)', 'Programa Bolsa Família (Lei 10.836, de 2004)', 'Lei da Ficha Limpa (Lei Complementar 135, de 2010)'],
  },
  {
    id: 'dilma',
    foto: 'dilma',
    nome: 'Dilma Rousseff',
    inicio: '2011-01-01',
    fim: '2016-08-31',
    chegada: 'Eleição direta (2010), primeira mulher na Presidência; reeleita em 2014.',
    saida: 'Afastada com a abertura do processo de impeachment no Senado (12/05/2016) e destituída pelo Senado em 31/08/2016.',
    marcos: ['Lei de Acesso à Informação (Lei 12.527, de 2011)', 'Comissão Nacional da Verdade (2012–2014)', 'Marco Civil da Internet (Lei 12.965, de 2014)'],
  },
  {
    id: 'temer',
    foto: 'temer',
    nome: 'Michel Temer',
    inicio: '2016-08-31',
    fim: '2019-01-01',
    chegada: 'Vice-presidente; exerceu a Presidência interinamente desde 12/05/2016 e assumiu em definitivo com a destituição de Dilma Rousseff.',
    saida: 'Fim do mandato.',
    marcos: ['Teto de gastos (Emenda Constitucional 95, de 2016)', 'Reforma trabalhista (Lei 13.467, de 2017)', 'Intervenção federal na segurança pública do Rio de Janeiro (2018)'],
  },
  {
    id: 'bolsonaro',
    foto: 'bolsonaro',
    nome: 'Jair Bolsonaro',
    inicio: '2019-01-01',
    fim: '2023-01-01',
    chegada: 'Eleição direta (2018).',
    saida: 'Fim do mandato.',
    marcos: ['Reforma da Previdência (Emenda Constitucional 103, de 2019)', 'Pandemia de covid-19 e Auxílio Emergencial (Lei 13.982, de 2020)', 'Autonomia do Banco Central (Lei Complementar 179, de 2021)'],
  },
  {
    id: 'lula-2023',
    foto: 'lula',
    nome: 'Luiz Inácio Lula da Silva',
    inicio: '2023-01-01',
    fim: null,
    chegada: 'Eleição direta (2022).',
    saida: null,
    marcos: ['Novo arcabouço fiscal (Lei Complementar 200, de 2023)', 'Reforma tributária sobre o consumo (Emenda Constitucional 132, de 2023)'],
    nota: 'Mandato até 05/01/2027: a Emenda Constitucional 111, de 2021, passou a posse presidencial para 5 de janeiro.',
  },
];
